[project]
name = "ex1001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rjsghk117", email = "rjsghk117@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.3",
    "langchain-openai>=1.6.7",
    "openai>=3.22.1",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ex1001 = "ex1001:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
